name: C:\Users\pawel\Anaconda3\envs\text_search
dependencies:
- levenshtein=0.12.0=py35_1
- pip=8.1.2=py35_0
- python=3.5.2=0
- setuptools=23.0.0=py35_0
- vs2015_runtime=14.0.25123=0
- wheel=0.29.0=py35_0
- pip:
  - python-levenshtein==0.12.0

